# Generated by Django 5.2.5 on 2025-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="category",
            name="slogan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
